export type Film = {
  id: string; title: string; category: string; label: string; poster: string;
  image: string; video: string; prompt: string; aspect: "16:9" | "9:16";
  color: string; description: string;
};
export const originalFilms: Film[] = [
  { id:"neon-city", title:"After the last train", category:"Cinema", label:"CINEMATIC STORYTELLING", poster:"/media/neon-city-poster.webp", image:"/media/neon-city.webp", video:"/media/neon-city.mp4", aspect:"16:9", color:"#b43a55", description:"Rain on the pavement. A city that never quite sleeps. One shot with a story to tell.", prompt:"A solitary woman in a dark coat walks away beneath a translucent umbrella on a rain-soaked futuristic city street. Crimson neon reflects in wet asphalt. A slow forward dolly follows her through fine rain and rising steam. Anamorphic cinematography, deep sapphire shadows, realistic architecture, one uninterrupted shot." },
  { id:"chrome-runner", title:"Designed to defy gravity", category:"Product", label:"PRODUCT IN MOTION", poster:"/media/chrome-runner-poster.webp", image:"/media/chrome-runner.webp", video:"/media/chrome-runner.mp4", aspect:"16:9", color:"#b58459", description:"A new angle on a familiar object. Light, texture, and a little impossibility.", prompt:"A single unbranded futuristic running shoe with satin silver panels, ivory mesh, and a vermilion sole floats above a polished black plinth. The shoe rotates slowly while an amber studio highlight travels across its surface. Subtle camera push, consistent product shape, luxury advertising cinematography." },
  { id:"astronaut-garden", title:"Life on the other side", category:"Worlds", label:"IMAGINED WORLDS", poster:"/media/astronaut-garden-poster.webp", image:"/media/astronaut-garden.webp", video:"/media/astronaut-garden.mp4", aspect:"16:9", color:"#67774c", description:"Somewhere between a distant planet and a place you almost remember.", prompt:"An astronaut stands inside a vast abandoned circular greenhouse on another planet. Lush ferns and small amber flowers fill the space. Beyond a monumental round opening, a ringed planet hangs in a pale blue sky. A gentle lateral camera glide, warm sunlight, drifting dust, delicate movement in the leaves, cinematic realism." },
  { id:"sculptural-fashion", title:"A moment, in vermilion", category:"Fashion", label:"VERTICAL STORIES", poster:"/media/sculptural-fashion-poster.webp", image:"/media/sculptural-fashion.webp", video:"/media/sculptural-fashion.mp4", aspect:"9:16", color:"#aa4036", description:"A sculptural silhouette. A single turn. A frame made for the small screen.", prompt:"An adult fashion model with short dark hair wears an architectural vermilion pleated gown beside a curved concrete wall and pale limestone steps. Cobalt blue sky, strong afternoon light. She makes a slow graceful half-turn as fabric moves in the breeze. A subtle camera push, stable geometry, full-length vertical composition." },
];
export const creativeFilms: Film[] = [
  {id:"lantern-library",title:"A thousand unwritten worlds",category:"Worlds",label:"IMPOSSIBLE ARCHITECTURE",poster:"/media/lantern-library-poster.webp",image:"/media/lantern-library.webp",video:"/media/lantern-library.mp4",aspect:"16:9",color:"#9a613d",description:"A spiral of stories. A sky of lanterns. An invitation to get a little lost.",prompt:"A monumental circular library with spiraling walnut bookshelves and suspended staircases. Hundreds of glowing paper lanterns float through the immense hall. A tiny reader in a red coat gives scale. The camera glides slowly forward through warm amber light and drifting dust. Magical realism, coherent architecture, one uninterrupted shot."},
  {id:"paper-metropolis",title:"A city, folded into being",category:"Animation",label:"HANDCRAFTED WORLDS",poster:"/media/paper-metropolis-poster.webp",image:"/media/paper-metropolis.webp",video:"/media/paper-metropolis.mp4",aspect:"16:9",color:"#bc7c5c",description:"Paper, patience, and a small red tram. A whole city in a single fold.",prompt:"An intricate miniature city made from folded coral, butter yellow, mint and ivory paper. A tower slowly opens its accordion facade as a tiny red paper tram moves along its track. A gentle lateral camera slide reveals tactile folds and delicate bridges. Soft studio light, stop-motion character, consistent surrounding buildings."},
  {id:"ember-stag",title:"The forest holds its breath",category:"Cinema",label:"CINEMATIC FANTASY",poster:"/media/ember-stag-poster.webp",image:"/media/ember-stag.webp",video:"/media/ember-stag.mp4",aspect:"16:9",color:"#9a6c41",description:"A still clearing. A quiet encounter. A little magic between the trees.",prompt:"A majestic red deer stag stands in a dark old-growth forest, illuminated by a shaft of copper light. Warm firefly-like particles drift through gentle ground fog. The stag slowly turns its head and exhales a faint breath. A very slow camera push, realistic fur and anatomy, stable antlers, atmospheric cinema."},
  {id:"prism-bloom",title:"Light learns to bloom",category:"Art & motion",label:"MATERIAL EXPLORATIONS",poster:"/media/prism-bloom-poster.webp",image:"/media/prism-bloom.webp",video:"/media/prism-bloom.mp4",aspect:"9:16",color:"#8c629e",description:"A flower made of glass. A passing light. Color that feels almost alive.",prompt:"A single iridescent blown-glass flower floats upright against a deep plum-black studio background. Its delicate translucent petals refract pink, violet, cyan and gold. The flower rotates slowly by fifteen degrees while a narrow studio light travels across its surface. Physical glass optics, coherent petals, vertical macro framing."},
  {id:"kinetic-orbit",title:"Balance, beautifully impossible",category:"Art & motion",label:"KINETIC DESIGN",poster:"/media/kinetic-orbit-poster.webp",image:"/media/kinetic-orbit.webp",video:"/media/kinetic-orbit.mp4",aspect:"16:9",color:"#a96b51",description:"Copper in orbit. Geometry with a pulse. A study in controlled impossibility.",prompt:"Three polished copper elliptical bands float around a matte ivory sphere above a low black stone plinth in a dark gallery. The bands rotate independently at a slow mechanical pace while the sphere remains stationary. Controlled warm reflections, consistent geometry, restrained museum lighting and an almost imperceptible camera push."},
];
export const showcaseFilms: Film[] = [...creativeFilms, ...originalFilms];
