import Link from "next/link";
import { ArrowUpRight, Aperture, LockKeyhole, Fingerprint, ScanLine, Plus } from "lucide-react";
import { AmbientVideo, Reveal } from "@/components/site/motion";
import { CinematicHero } from "@/components/site/cinematic-hero";
import { creativeFilms } from "@/lib/showcase";
import { posts } from "@/lib/site-content";
export default function Landing(){return <>
<CinematicHero/>
<section className="model-ribbon"><span>YOUR IMAGINATION, MEET YOUR TOOLS.</span><div><strong>MiniMax <b>H3</b></strong><i/><strong>LTX <b>2.5</b></strong><i/><span>Built on Bittensor</span></div><a href="/models">Meet the models <ArrowUpRight size={15}/></a></section>
<section id="possibilities" className="section-pad possibility-section"><Reveal className="section-intro"><span className="section-kicker">01 / MAKE THE UNSEEN</span><div><h2>Some ideas need<br/>more than <em>words.</em></h2><p>A scene you’ve never visited. A story you haven’t told.<br/>Start with an idea. Give it movement. Make it yours.</p></div><a className="text-link" href="/studio">Step into the studio <ArrowUpRight size={17}/></a></Reveal><div className="creation-stories"><Reveal className="story-large"><a href="/studio?scene=paper-metropolis" className="image-story"><img src="/media/paper-metropolis.webp" alt="A colorful miniature city built from folded paper" loading="lazy"/><span className="image-story-number">01 / TEXT TO VIDEO</span><div><h3>If you can describe it,<br/>you can begin it.</h3><span>Start with a few words <ArrowUpRight size={18}/></span></div></a></Reveal><Reveal className="story-small"><a href="/studio?mode=image_to_video" className="image-story"><img src="/media/prism-bloom.webp" alt="An iridescent blown-glass flower against a dark studio backdrop" loading="lazy"/><span className="image-story-number">02 / IMAGE TO VIDEO</span><div><h3>A still image.<br/>An entirely new story.</h3><span>Bring a frame to life <ArrowUpRight size={18}/></span></div></a><div className="story-caption"><Aperture size={25} strokeWidth={1}/><p>Choose the frame.<br/><span>You decide what happens next.</span></p><a href="/docs#creation-modes" aria-label="Read about creation modes"><ArrowUpRight size={20}/></a></div></Reveal></div></section>
<section className="creative-marquee" aria-label="Creative possibilities"><div aria-hidden="true">CINEMA <span>✳</span> PRODUCT <span>✳</span> FASHION <span>✳</span> NEW WORLDS <span>✳</span></div><a href="/use-cases">Made for whatever comes next <ArrowUpRight size={18}/></a></section>
<section className="flow-section"><div className="flow-heading"><span className="section-kicker">02 / FIND YOUR FLOW</span><h2>From a spark.<br/>To <em>something real.</em></h2><p>A space to experiment. The control to be intentional.</p><a className="ocean-button button-dark" href="/studio">Open the studio <ArrowUpRight size={17}/></a></div><div className="flow-steps">{[{n:"01",title:"Let the idea in.",copy:"Write your scene or bring a reference image. A place, a feeling, a moment—start anywhere."},{n:"02",title:"Make it your own.",copy:"Pick your model, frame your shot, and set the pace. From a quick experiment to a considered composition."},{n:"03",title:"Take it into the world.",copy:"Preview your result and download the video with its signed receipt. Keep creating from there."}].map(s=><Reveal key={s.n} className="flow-step"><span>{s.n}</span><div><h3>{s.title}</h3><p>{s.copy}</p></div><Plus size={20} strokeWidth={1}/></Reveal>)}</div></section>
<section className="horizon-section"><AmbientVideo src="/media/lantern-library.mp4" poster="/media/lantern-library-poster.webp"/><div className="horizon-scrim"/><Reveal className="horizon-copy"><span className="section-kicker">ROOM TO WANDER. SPACE TO CREATE.</span><h2>The only limit<br/>is where you<br/><em>stop imagining.</em></h2><a href="/studio" className="ocean-button button-white">Go a little further <ArrowUpRight size={18}/></a></Reveal></section>
<section className="section-pad showcase-section"><Reveal className="section-intro"><span className="section-kicker">03 / A LITTLE INSPIRATION</span><div><h2>Every world starts<br/>with <em>a what if.</em></h2><p>A woodland encounter. A folded city. A sculpture that refuses to stand still.</p></div><a className="text-link" href="/showcase">Enter the screening room <ArrowUpRight size={17}/></a></Reveal><div className="ocean-showcase">{[creativeFilms[2],creativeFilms[1],creativeFilms[4]].map((s,i)=><Reveal key={s.id} className={`showcase-card showcase-${i}`}><div className="showcase-media"><AmbientVideo src={s.video} poster={s.poster}/><span className="showcase-label">{s.label}</span></div><a href={`/studio?scene=${s.id}`}><div><small>STUDY 0{i+1}</small><h3>{s.title}</h3></div><ArrowUpRight size={20}/></a></Reveal>)}</div><p className="showcase-note">Original visual studies generated through OpenRouter. These are creative examples, not KunoWorld model benchmarks.</p></section>
<section className="privacy-section"><Reveal className="privacy-title"><span className="section-kicker">04 / YOUR WORLD BELONGS TO YOU</span><h2>Create freely.<br/><em>Know the journey.</em></h2><p>Private creation and verifiable origins are at the heart of KunoWorld’s protocol.</p><a href="/privacy" className="text-link">How privacy works <ArrowUpRight size={17}/></a></Reveal><div className="privacy-features">{[{icon:LockKeyhole,title:"Private from the first word.",copy:"The SDK encrypts prompts and reference media on your device before sending them to the gateway."},{icon:Fingerprint,title:"An origin you can inspect.",copy:"Every completed protocol job returns a signed receipt, checked against the video by your SDK."},{icon:ScanLine,title:"Built to be verifiable.",copy:"Worker identity and evidence are bound to the generation. Hardware verification remains in development."}].map(c=><Reveal className="privacy-feature" key={c.title}><c.icon size={24} strokeWidth={1.3}/><div><h3>{c.title}</h3><p>{c.copy}</p></div></Reveal>)}</div><p className="privacy-status">Development preview · Real GPU inference and production hardware attestation are still being completed. <a href="/docs#project-status">Read project status <ArrowUpRight size={12}/></a></p></section>
<section className="developer-band"><div><span className="section-kicker">FOR THE BUILDERS OF NEW WORLDS</span><h2>Your vision.<br/>Your application.<br/><em>Our video protocol.</em></h2><p>Bring encrypted video creation into the tools you’re building, with JavaScript and Python SDKs.</p><div className="button-row"><a href="/developers" className="ocean-button button-dark">Build with KunoWorld <ArrowUpRight size={17}/></a><a href="/api" className="text-link">Explore the API <ArrowUpRight size={15}/></a></div></div><div className="landing-code"><div><span/><span/><span/><p>your-next-world.ts</p></div><pre><span className="code-muted">{'// A little code. A world of possibility.'}</span>{'\n\n'}<span className="code-lilac">const</span>{' job = '}<span className="code-lilac">await</span>{' kuno.submit({\n  '}<span className="code-mint">prompt</span>{': '}<span className="code-sand">{'"A city unfolding from a sheet of paper."'}</span>{',\n  '}<span className="code-mint">model</span>{': '}<span className="code-sand">{'"ltx-2.5-fast"'}</span>{',\n  durationS: 5,\n});\n\n'}<span className="code-lilac">const</span>{' { video, receipt } =\n  '}<span className="code-lilac">await</span>{' kuno.wait(job);'}</pre><a href="/docs#quickstart">Start with the complete example <ArrowUpRight size={14}/></a></div></section>
<section className="section-pad journal-section"><Reveal className="section-intro"><span className="section-kicker">THE KUNOWORLD JOURNAL</span><div><h2>Notes from<br/><em>the imagination.</em></h2></div><Link href="/blog" className="text-link">All stories <ArrowUpRight size={17}/></Link></Reveal><div className="journal-grid">{posts.slice(0,3).map(p=><a href={`/blog/${p.slug}`} className="journal-card" key={p.slug}><div className="journal-image"><img src={p.image} alt="" loading="lazy"/><ArrowUpRight size={20}/></div><span>{p.category} <i>•</i> {p.read}</span><h3>{p.title}</h3></a>)}</div></section>
<section className="landing-platform-links"><span className="section-kicker">A COMPLETE CREATIVE WORKSPACE</span><h2>Find your way<br/><em>into KunoWorld.</em></h2><div>{[{title:"The studio",copy:"Describe. Direct. Create.",href:"/studio",number:"01"},{title:"The possibilities",copy:"Your next project starts with a what if.",href:"/use-cases",number:"02"},{title:"The developer tools",copy:"Put the protocol inside your own product.",href:"/developers",number:"03"}].map(c=><a key={c.title} href={c.href}><span>{c.number}</span><div><h3>{c.title}</h3><p>{c.copy}</p></div><ArrowUpRight size={24}/></a>)}</div></section>
<section className="final-horizon"><img src="/media/prism-bloom.webp" alt="Prismatic light refracting through a sculptural glass flower" loading="lazy"/><div/><span>THE NEXT FRAME IS YOURS.</span><h2>Go on.<br/><em>Make a world.</em></h2><a href="/studio" className="ocean-button button-white">Start creating <ArrowUpRight size={18}/></a></section>
</>}
