"use client";
import { usePathname } from "next/navigation";
import { useEffect, useState, type ReactNode } from "react";
import { LogoMark } from "@/components/site/LogoMark";
import { ArrowUpRight, Menu, X, ArrowRight } from "lucide-react";
import { Sheet, SheetContent, SheetTitle, SheetDescription, SheetHeader, SheetTrigger, SheetClose } from "@/components/ui/sheet";
const links = [{href:"/studio",label:"Studio"},{href:"/showcase",label:"Showcase"},{href:"/use-cases",label:"Use cases"},{href:"/models",label:"Models"},{href:"/developers",label:"Developers"},{href:"/blog",label:"Journal"}];
export function SiteShell({children}:{children:ReactNode}) {
 const path=usePathname();const home=path==="/";const [scrolled,setScrolled]=useState(false);const [open,setOpen]=useState(false);
 useEffect(()=>{let pending=false;const update=()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{setScrolled(window.scrollY>50);pending=false;});};update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update);},[]);
 useEffect(()=>setOpen(false),[path]);
 useEffect(()=>{
   if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;
   const surfaces=Array.from(document.querySelectorAll<HTMLElement>(".horizon-section, .creative-marquee"));
   let frame:number|null=null;
   const update=()=>{if(frame!==null)return;frame=requestAnimationFrame(()=>{for(const el of surfaces){const r=el.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight){const progress=(innerHeight-r.top)/(innerHeight+r.height);el.style.setProperty("--scene-progress",String(progress));}}frame=null;});};
   update();window.addEventListener("scroll",update,{passive:true});
   return()=>{window.removeEventListener("scroll",update);if(frame!==null)cancelAnimationFrame(frame);};
 },[path]);
 return <div className={`ocean-site ${home?"home-site":"inner-site"}`}><a className="skip-link" href="#page-content">Skip to content</a><header className={`ocean-nav ${scrolled?"is-scrolled":""}`}><a href="/" className="ocean-brand" aria-label="KunoWorld home"><LogoMark size={26}/><span>kunoworld</span></a><nav className="desktop-nav" aria-label="Main navigation">{links.map(l=><a href={l.href} key={l.href} aria-current={path===l.href?"page":undefined}>{l.label}</a>)}</nav><div className="nav-end"><a className="nav-docs" href="/docs">Docs <ArrowUpRight size={13}/></a><a href="/studio" className="nav-create">Start creating <ArrowUpRight size={15}/></a><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-nav-trigger" aria-label="Open navigation"><Menu size={23}/></button></SheetTrigger><SheetContent className="ocean-mobile-nav"><SheetHeader><SheetTitle>KunoWorld</SheetTitle><SheetDescription>A world of your own.</SheetDescription></SheetHeader><nav aria-label="Mobile navigation">{[...links,{href:"/docs",label:"Documentation"},{href:"/api",label:"API reference"},{href:"/about",label:"About"}].map(l=><SheetClose key={l.href} asChild><a href={l.href}>{l.label}<ArrowUpRight size={20}/></a></SheetClose>)}</nav></SheetContent></Sheet></div></header><main id="page-content">{children}</main><footer className="ocean-footer"><div className="footer-top"><div><a href="/" className="ocean-brand"><LogoMark size={27}/><span>kunoworld</span></a><p>A little imagination.<br/>A world of possibility.</p></div><div className="footer-column"><span>CREATE</span><a href="/studio">Video studio</a><a href="/showcase">Screening room</a><a href="/use-cases">Use cases</a><a href="/models">Explore models</a><a href="/blog">Creative journal</a></div><div className="footer-column"><span>BUILD</span><a href="/developers">Developers</a><a href="/docs">Documentation</a><a href="/api">API reference</a></div><div className="footer-column"><span>KUNOWORLD</span><a href="/about">Our vision</a><a href="/privacy">Privacy & provenance</a><a href="/verify">Verify a film</a><a href="/docs#project-status">Project status</a></div></div><div className="footer-wordmark" aria-hidden="true">a world of your own.</div><div className="footer-bottom"><span>© 2026 KunoWorld</span><span>Independent imagination. Verifiable creation.</span><a href="/studio">See you in the studio <ArrowUpRight size={13}/></a></div></footer></div>;
}
